export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";
export const TOGGLE_MENU = "TOGGLE_MENU";

export const HANDLE_CHANGE = "HANDLE_CHANGE";
export const CLEAR_POST = "CLEAR_POST";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const GET_POSTS_BEGIN = "GET_POSTS_BEGIN";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";

export const GET_ALL_POSTS_BEGIN = "GET_ALL_POSTS_BEGIN";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";

export const SET_EDIT_POST = "SET_EDIT_POST";

export const EDIT_POST_BEGIN = "EDIT_POST_BEGIN";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const GET_PROFILE_BEGIN = "GET_PROFILE_BEGIN";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

export const NO_MORE_POSTS = "NO_MORE_POSTS";

export const LIKE_A_POST = "LIKE_A_POST";
export const MAKE_A_COMMENT = "MAKE_A_COMMENT";
export const LOAD_COMMENTS = "LOAD_COMMENTS";
export const GET_REPLIES = "GET_REPLIES";
